FROM fedora:29
RUN dnf install -y golang libpcap-devel
WORKDIR /root/go/src/github.com/comcast/ravel
COPY . $WORKDIR
RUN go build -v -o kube2ipvs ./cmd


FROM alpine:3.8
MAINTAINER RDEI Team <rdei@comcast.com>

RUN echo '@edgemain http://dl-3.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories
RUN apk update
RUN apk add libpcap
RUN apk add ipvsadm@edgemain
RUN apk add iptables
RUN rm -rf /var/cache/apk/*

COPY --from=0 /root/go/src/github.com/comcast/ravel/kube2ipvs /bin/
ENTRYPOINT ["/bin/kube2ipvs"]
