package haproxy

var haproxyConfig string = `
# Autogenerated by Ravel. Do not change.


global
    log 127.0.0.1        local0
    log 127.0.0.1        local1 notice
    maxconn              4096
    user                 haproxy
    group                haproxy

defaults
    log                     global
    mode                    tcp
    option                  dontlognull
    retries                 3
    maxconn                 28000
    timeout connect         5000
    timeout client          50000
    timeout server          50000

{{ range . }}
listen listen6-{{ .Port }}
        bind	{{ .Source }}:{{ .Port }}
        mode    tcp
        server  dest4-{{ .Port }}    {{ .Dest }}
        maxconn 28000
        grace   4000
{{ end }}
`
